--1.
SELECT E.EMP_NO, E.LAST_NAME, E.FIRST_NAME, E.GENDER, COALESCE(S.SALARY,0) AS SALARY
FROM EMPLOYEES E
LEFT JOIN SALARIES S ON(E.EMP_NO = S.EMP_NO)
ORDER BY E.EMP_NO;

--2.
SELECT E.EMP_NO, E.LAST_NAME, E.FIRST_NAME, E.GENDER, COALESCE(S.SALARY,0) AS SALARY
FROM EMPLOYEES E
LEFT JOIN SALARIES S ON(E.EMP_NO = S.EMP_NO)
WHERE DATE_PART('YEAR', E.HIRE_DATE) = 1986
ORDER BY E.EMP_NO;

--3.
SELECT DM.DEPT_NO, D.DEPT_NAME, E.EMP_NO, E.LAST_NAME, E.FIRST_NAME, DM.FROM_DATE, DM.TO_DATE
FROM DEPT_MANAGER DM
INNER JOIN EMPLOYEES E ON(DM.EMP_NO = E.EMP_NO)
INNER JOIN DEPARTMENTS D ON(DM.DEPT_NO = D.DEPT_NO)
ORDER BY DM.DEPT_NO, D.DEPT_NAME, E.EMP_NO, E.LAST_NAME, E.FIRST_NAME, DM.FROM_DATE, DM.TO_DATE;

--4.
SELECT E.EMP_NO, E.LAST_NAME, E.FIRST_NAME, D.DEPT_NAME
FROM DEPT_EMP DE
INNER JOIN EMPLOYEES E ON(DE.EMP_NO = E.EMP_NO)
INNER JOIN DEPARTMENTS D on(DE.DEPT_NO = D.DEPT_NO)
ORDER BY E.EMP_NO;

--5.
SELECT E.EMP_NO, E.LAST_NAME, E.FIRST_NAME, E.GENDER, COALESCE(S.SALARY,0) AS SALARY
FROM EMPLOYEES E
LEFT JOIN SALARIES S ON(E.EMP_NO = S.EMP_NO)
WHERE UPPER(E.FIRST_NAME) = 'HERCULES'
AND UPPER(E.LAST_NAME) LIKE 'B%'
ORDER BY E.EMP_NO;

--6.
SELECT E.EMP_NO, E.LAST_NAME, E.FIRST_NAME, D.DEPT_NAME
FROM DEPT_EMP DE
INNER JOIN EMPLOYEES E ON(DE.EMP_NO = E.EMP_NO)
INNER JOIN DEPARTMENTS D on(DE.DEPT_NO = D.DEPT_NO)
WHERE UPPER(D.DEPT_NAME) = 'SALES'
ORDER BY E.EMP_NO;

--7.
SELECT E.EMP_NO, E.LAST_NAME, E.FIRST_NAME, D.DEPT_NAME
FROM DEPT_EMP DE
INNER JOIN EMPLOYEES E ON(DE.EMP_NO = E.EMP_NO)
INNER JOIN DEPARTMENTS D on(DE.DEPT_NO = D.DEPT_NO)
WHERE UPPER(D.DEPT_NAME) in('SALES','DEVELOPMENT')
ORDER BY E.EMP_NO;

--8.  
SELECT E.LAST_NAME, COUNT(*) AS COUNTS
FROM EMPLOYEES E
GROUP BY E.LAST_NAME
ORDER BY COUNT(*) DESC;
