DROP TABLE IF EXISTS DEPT_EMP;
DROP TABLE IF EXISTS DEPT_MANAGER;
DROP TABLE IF EXISTS SALARIES;
DROP TABLE IF EXISTS TITLE;

DROP TABLE IF EXISTS DEPARTMENTS;
DROP TABLE IF EXISTS EMPLOYEES;


CREATE TABLE DEPARTMENTS 
(
	DEPT_NO VARCHAR(255) PRIMARY KEY,
	DEPT_NAME VARCHAR(255) NULL
);

CREATE TABLE EMPLOYEES
(
	EMP_NO INTEGER PRIMARY KEY,
	BIRTH_DATE DATE NULL,
	FIRST_NAME VARCHAR(255) NULL,
	LAST_NAME VARCHAR(255) NULL,
	GENDER VARCHAR(255) NULL,
	HIRE_DATE DATE NULL
);

CREATE TABLE DEPT_EMP
(
	EMP_NO INTEGER NOT NULL,
	DEPT_NO VARCHAR(255) NOT NULL,
	FROM_DATE DATE NULL,
	TO_DATE DATE NULL,
	FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES(EMP_NO),
	FOREIGN KEY (DEPT_NO) REFERENCES DEPARTMENTS(DEPT_NO)
);

CREATE TABLE DEPT_MANAGER
(
	DEPT_NO VARCHAR(255) NOT NULL,
	EMP_NO INTEGER NOT NULL,
	FROM_DATE DATE NULL,
	TO_DATE DATE NULL,
	FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES(EMP_NO),
	FOREIGN KEY (DEPT_NO) REFERENCES DEPARTMENTS(DEPT_NO)
);

CREATE TABLE SALARIES
(
	EMP_NO INTEGER NOT NULL,
	SALARY FLOAT NOT NULL,
	FROM_DATE DATE NULL,
	TO_DATE DATE NULL,
	FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES(EMP_NO)
);

CREATE TABLE TITLE
(
	EMP_NO INTEGER NOT NULL,
	TITLE VARCHAR(255) NOT NULL,
	FROM_DATE DATE NULL,
	TO_DATE DATE NULL,
	FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES(EMP_NO)
);




